export const pl = {
  dialog: {
    'BAN_AUDIT_REASON': 'Zbanowano przez {{TAG}}{{REASON}}',
    'BAN_CANCELLED': 'Ban anulowany.',
    'BAN_CONFIRM': 'Użytkownik {{MEMBER}} został zbanowany z serwera{{REASON}}',
    'BAN_DM_MESSAGE': 'Zostałeś zbanowany z serwera `{{GUILD}}`{{REASON}}',
    'BAN_TIMEOUT': 'Czas minął. Użytkownik nie został zbanowany.',
    'CONFIRM_BAN': 'Czy na pewno chcesz zbnanować {{MEMBER}}? Odpowiedz `cancel` aby anulować.',
  },
  errors: {
    command: {
      'NO_TARGET': 'Podano nieprawdłowy cel - Nikt nie został wzmieniony lub podane ID było nieprawidłowe.',
      'NOT_BANNABLE': 'Nie możesz zbanować tego użytkownika.',
      'NOT_BANNABLE_ME': 'Nie mogę zbanować tego użytkownika.',
      'NOT_BANNABLE_OWNER': 'Właściciel serwera nie może zostać zbanowany.',
      'NOT_BANNABLE_SELF': 'Nie możesz zbanować sam siebie.',
    },
    eventHandler: {
      'ARGS_REQUIRED': 'Ta komenda wymaga podania argumentów, żadnych jednak nie podano.',
      'COMMAND_DISABLED': 'Niestety, ale ta komenda jest w tej chwili wyłączona globalnie.',
      'COMMAND_DISABLED_GUILD': 'Niestety, ale ta komenda jest niedostępna dla tego serwera.',
      'COMMAND_NOT_ENABLED': 'Niestety, ale ta komenda jest dostępna tylko dla wybranych serwerów.',
      'COMMAND_NOT_ENABLED_GUILD': 'Niestety, ale ta komenda nie jest dostępna dla wszystkich serwerów - wliczając w to ten serwer.',
      'GUILD_ONLY': 'Ta komenda nie może być użyta w wiadomościach prywatnych.',
      'NO_PERMS': 'Brakuje Ci pozwoleń do użycia tej komendy:',
      'OWNER_ONLY': 'Ta komenda może być użyta tylko przez właścicieli bota.',
      'USER_BLACKLISTED': 'Zostałeś zablokowany z używania tego bota.\nJeśli twierdzisz że to pomyłka, dołącz do oficjalnego serwera bota i wyjaśnij sytuację (zaproszenie jest zawsze dostępne poprzez komendę `support`).',
    },
    util: {
      'MEMBER_NULL': 'Nie podano członka serwera.',
    },
  },
  permissions: {
    'ADD_REACTIONS': 'Dodawanie reakcji',
    'ADMINISTRATOR': 'Administrator',
    'ATTACH_FILES': 'Załączanie plików',
    'BAN_MEMBERS': 'Banowanie członków',
    'CHANGE_NICKNAME': 'Zmiana pseudonimu',
    'CONNECT': 'Łączenie',
    'CREATE_INSTANT_INVITE': 'Tworzenie zaproszeń',
    'DEAFEN_MEMBERS': 'Wyciszanie dźwięku członkom czatu głosowego',
    'EMBED_LINKS': 'Zamieszczanie linków',
    'KICK_MEMBERS': 'Wyrzucanie członków',
    'MANAGE_CHANNELS': 'Zarządzanie kanałami',
    'MANAGE_EMOJIS': 'Zarządzanie emoji',
    'MANAGE_GUILD': 'Zarządzanie serwerem',
    'MANAGE_MESSAGES': 'Zarządzanie wiadomościami',
    'MANAGE_NICKNAMES': 'Zarządzanie pseudonimami',
    'MANAGE_ROLES': 'Zarządzanie rolami',
    'MANAGE_WEBHOOKS': 'Zarządzanie webhookami',
    'MENTION_EVERYONE': 'Wzmienianie everyone i wszystkich ról',
    'MOVE_MEMBERS': 'Przenoszenie członków czatu głosowego',
    'MUTE_MEMBERS': 'Wyciszanie mikrofonu członkom czatu głosowego',
    'PRIORITY_SPEAKER': 'Priorytetowy rozmówca',
    'READ_MESSAGE_HISTORY': 'Czytanie historii czatu',
    'SEND_MESSAGES': 'Wysyłanie wiadomości',
    'SEND_TTS_MESSAGES': 'Wysyłanie wiadomości TTS',
    'SPEAK': 'Mówienie',
    'STREAM': 'Streamowanie',
    'USE_EXTERNAL_EMOJIS': 'Używanie zewnętrznych emoji',
    'USE_VAD': 'Używanie aktywacji głosowej',
    'VIEW_AUDIT_LOG': 'Wyświetlanie dziennika zdarzeń',
    'VIEW_CHANNEL': 'Wyświetlanie i czytanie kanałów',
    'VIEW_GUILD_INSIGHTS': 'Wyświetlanie danych serwera',
  },
};